version: '3'
services:
    db:
        container_name: isp-db
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - "./mongo-volume:/data/db"
    api:
        container_name: isp-api
        build: ./server
        restart: always
        depends_on: 
            - db
        ports:
            - "3000:3000"
        volumes:
            - "./json-volume:/usr/src/app/db_storage"
    frontend:
        container_name: isp-frontend
        build: ./client
        restart: always
        depends_on: 
            - db
        ports:
            - "8080:80"
volumes:
    mongo-volume:
        external: false
    json-volume:
        external: false
    